/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    'antd',
    '@ant-design/icons',
    '@ant-design/nextjs-registry',
    'rc-util',
    'rc-pagination',
    'rc-picker',
    'rc-field-form',
    'rc-footer',
    'rc-input',
    'rc-menu',
    'rc-motion',
    'rc-notification',
    'rc-progress',
    'rc-select',
    'rc-table',
    'rc-tabs',
    'rc-textarea',
    'rc-tooltip',
    'rc-tree',
    'rc-tree-select',
    'rc-upload',
    'rc-checkbox',
    'rc-cascader',
    'rc-dialog',
    'rc-drawer',
    'rc-dropdown',
    'rc-image',
    'rc-input-number',
    'rc-rate',
    'rc-resize-observer',
    'rc-segmented',
    'rc-slider',
    'rc-steps',
    'rc-switch',
    'rc-virtual-list',
  ],
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'i.pravatar.cc' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'media.clowand.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
    ],
  },
};

module.exports = nextConfig;
